// REACT
import { useEffect, useState } from 'react';

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../../utils/getMenu';
import getLabPage from '../../utils/getLabPage';
import getPeople from '../../utils/getPeople';
import getRoles from '../../utils/getRoles';

// COMPONENTS
import Layout from '../../components/Layout/Layout';
import LabGroup from '../../components/LabGroup/LabGroup';
import AlternatingContainer from '../../components/AlternatingContainer/AlternatingContainer';
import PersonCategory from '../../components/PersonCategory/PersonCategory';
import Alumni from '../../components/Alumni/Alumni';
import Alumnus from '../../components/Alumnus/Alumnus';

// ----------------------------------------
// ----------------------------------------

export default function Lab({menuItems}) {
    const [page, setPage] = useState(null);
    const [people, setPeople] = useState([]);
    const [roles, setRoles] = useState([]);

    useEffect(() => {
        getLabPage()
            .then( res => {
                console.log(res);
                setPage(res);
            })
            .catch( err => {
                console.log(err);
            })
        getPeople()
            .then( res => {
                console.log(res);
                setPeople(res)
            })
            .catch( err => {
                console.log(err)
            })
        getRoles()
            .then( res => {
                console.log(res);
                setRoles(res);
            })
            .catch( err => {
                console.log(err);
            })
    }, [])
    
    const filterPeopleByLab = (lab) => {
        return people.filter( person => person.lab == lab && !person.alumni);
    }

    const conditionalContent = () => {
        if (page && page.content && page.content.length > 0) {
            return page.content.map( section => {
                if (section._type == "labGroup") {
                    return <LabGroup group={section} key={section._key} people={filterPeopleByLab(section.lab)} roles={roles}/>
                } else {
                    // TODO RETURN non-lab-group section (images & text?)
                    return 
                }
            })
        }
    }

    const mapAlumni = () => {
        return (
            <PersonCategory categoryName={""} singleColumn={true}>
                <h1>Alumni</h1>
                <Alumni>
                    {getAlumni().sort((a, b) => {return a.lastName.toLowerCase() > b.lastName.toLowerCase() ? 1 : -1}).map( person => {
                    return (
                        <Alumnus person={person} key={person._id} />
                    )
                    })}
                </Alumni>
            </PersonCategory>
        )
    }

    const getAlumni = () => {
        return people.filter(person => person.alumni)
    }

  return (
    <>
      <Head>
        <title>Lab :: Zernicka-Goetz Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout menuItems={menuItems}>
          <AlternatingContainer>
              {conditionalContent()}
              {getAlumni().length > 0 && mapAlumni(getAlumni())}
          </AlternatingContainer>
      </Layout>

    </>
  )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}