// REACT
import { useEffect, useState } from 'react';

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../../utils/getMenu';
import getLabPage from '../../utils/getLabPage';
import getPeople from '../../utils/getPeople';

// COMPONENTS
import Layout from '../../components/Layout/Layout';
import Container from '../../components/Container/Container';
import LabGroup from '../../components/LabGroup/LabGroup';

// ----------------------------------------
// ----------------------------------------

export default function Lab({menuItems}) {
    const [page, setPage] = useState(null);
    const [people, setPeople] = useState([]);

    useEffect(() => {
        getLabPage()
            .then( res => {
                console.log(res);
                setPage(res);
            })
            .catch( err => {
                console.log(err);
            })
        getPeople()
            .then( res => {
                setPeople(res)
            })
            .catch( err => {
                console.log(err)
            })
    }, [])
    

    const conditionalContent = () => {
        if (page && page.content && page.content.length > 0) {
            return page.content.map( section => {
                if (section._type == "labGroup") {
                    return <LabGroup group={section} people={getPeople(section.lab)}/>
                } else {
                    // TODO RETURN non-lab-group section (images & text?)
                    return 
                }
            })
        }
    }

  return (
    <>
      <Head>
        <title>Lab :: Zernicka-Goetz Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout menuItems={menuItems}>
          <Container>
              {conditionalContent()}
          </Container>
      </Layout>

    </>
  )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}