// REACT
import { useEffect, useState } from "react";

// NEXT JS
import Head from 'next/head';

// UTILITIES
import getMenu from "../../utils/getMenu";
import getFunders from "../../utils/getFunders";

// COMPONENTS
import styles from '../../styles/FundersPage.module.scss';
import Layout from '../../components/Layout/Layout';
import AlternatingContainer from "../../components/AlternatingContainer/AlternatingContainer";
import ResponsiveImage from "../../components/ResponsiveImage/ResponsiveImage";
import getPage from "../../utils/getPage";
import PageSection from "../../components/PageSection/PageSection";
import RichBlocks from "../../components/RichBlocks/RichBlocks";

// ----------------------------------------
// ----------------------------------------

const Funder = ({funder}) => {
    return (
        <div className={styles.funder}>
            <ResponsiveImage img={funder.image} />
        </div>
    )
}


const Funding = ({menuItems}) => {
    const [funders, setFunders] = useState([]);
    const [donate, setDonate] = useState(null)

    useEffect(() => {
        getFunders()
            .then( res => {
                console.log(res);
                setFunders(res);
            })
            .catch( err => {
                console.log(err);
            })
        getPage('donate')
            .then( res => {
                console.log(res);
                setDonate(res);
            })
            .catch( err => {
                console.log(err);
            })
    }, []);

    return (
        <>
            <Head>
                <title>Funding :: Zernicka-Goetz Lab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout menuItems={menuItems}>
                <AlternatingContainer>
                    <div className={styles.fundersContainer}>
                        <h1>Our Funders</h1>
                        <h4>We are most grateful for support from:</h4>
                        <h2>Cambridge Lab</h2>
                        <div className={styles.fundersInnerContainer}>
                            {funders && funders.length > 0 && funders.filter(f => f.lab == "cambridge").map( (funder, i) => <Funder key={i} funder={funder} />)}
                        </div>
                        <h2>CalTech Lab</h2>
                        <div className={styles.fundersInnerContainer}>
                        {funders && funders.length > 0 && funders.filter(f => f.lab == "caltech").map( (funder, i) => <Funder key={i} funder={funder} />)}
                        </div>
                    </div>
                    <div className={styles.donateContainer}>
                        <h1 id="donate">Donate</h1>
                        {donate && donate.content && donate.content.length > 0 && donate.content.map( (section, i) => <RichBlocks key={i} blocks={section.text} />)}
                    </div>
                </AlternatingContainer>
            </Layout>
        </>
    )
}
export default Funding;

export async function getStaticProps({params}) {
    const menuItems = await getMenu();
    return {
      props: { menuItems }
    }
}