// STYLES
import styles from '../../styles/PublicationPage.module.scss';

// REACT
import { useEffect, useMemo, useState } from 'react';

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../../utils/getMenu';
import getPublications from '../../utils/getPublications';
import { getTags } from '../../components/PublicationList/PublicationListUtilities';

// COMPONENTS
import Layout from '../../components/Layout/Layout';
import Container from '../../components/Container/Container';
import PublicationList from '../../components/PublicationList/PublicationList';
import ButtonIcon from '../../components/ButtonIcon/ButtonIcon';
import Filter from '../../components/Filter/Filter';

// CONTEXTS
import { SearchFilterProvider } from '../../contexts/searchFilterContext';


export default function Home({menuItems}) {
    const [pubs, setPubs] = useState([]);
    const [filterOpen, setFilterOpen] = useState(false);
    
    useEffect(() => {
        getPublications()
            .then( res => {
                setPubs(res);
            })
            .catch( err => {
                console.log(err);
            })
    }, []);

    const tags = useMemo(() => {
        console.log(getTags(pubs));
        return getTags(pubs);
    }, [pubs])

    return (
        <>
            <Head>
                <title>Publications :: Zernicka-Goetz Lab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout menuItems={menuItems} >
                <SearchFilterProvider>
                    {filterOpen ? 
                        <div className={styles.filterTab} onClick={() => setFilterOpen(false)}><ButtonIcon type="close" callback={() => null}/></div> 
                        : <div className={styles.filterTab} onClick={() => setFilterOpen(true)}><ButtonIcon type="filter" callback={() => null}/></div>
                    }
                    <Filter open={filterOpen} setFilterOpen={setFilterOpen} tags={tags}/>
                    <Container>
                        <PublicationList pubs={pubs} />
                    </Container>
                </SearchFilterProvider>
            </Layout>
        </>
    )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}