// STYLES

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../../utils/getMenu';
import getPublications from '../../utils/getPublications';

// COMPONENTS
import Layout from '../../components/Layout/Layout';
import Container from '../../components/Container/Container';
import PublicationList from '../../components/PublicationList/PublicationList';
import { useEffect, useState } from 'react';

export default function Home({menuItems}) {
    const [pubs, setPubs] = useState([]);
    
    useEffect(() => {
        getPublications()
            .then( res => {
                setPubs(res);
            })
            .catch( err => {
                console.log(err);
            })
    }, [])

    const chunkPubsByYear = (pubs) => {
        let prevYear = null;
        return pubs.reduce( (prev, curr) => {
            // if current pub date is a new year
            let year = new Date(curr.pubDate).toLocaleDateString('en', {year: "numeric"});

            if ( prev.length == 0 || year != prevYear ) {
                prev.push([curr]);
            } else {
                prev[prev.length - 1].push(curr);
            }

            prevYear = year;
            return prev;
        }, [])
    }

    return (
        <>
            <Head>
                <title>Publications :: Zernicka-Goetz Lab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout menuItems={menuItems}>
                <Container>
                    <PublicationList pubs={chunkPubsByYear(pubs)} />
                </Container>
            </Layout>
        </>
    )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}