// STYLES

// REACT
import { useEffect, useState } from 'react';

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../../utils/getMenu';
import getPublications from '../../utils/getPublications';

// COMPONENTS
import Layout from '../../components/Layout/Layout';
import Container from '../../components/Container/Container';
import PublicationList from '../../components/PublicationList/PublicationList';
import ButtonIcon from '../../components/ButtonIcon/ButtonIcon';
import Filter from '../../components/Filter/Filter';

// CONTEXTS
import { SearchFilterProvider } from '../../contexts/searchFilterContext';


export default function Home({menuItems}) {
    const [pubs, setPubs] = useState([]);
    const [filterOpen, setFilterOpen] = useState(false);
    
    useEffect(() => {
        getPublications()
            .then( res => {
                setPubs(res);
            })
            .catch( err => {
                console.log(err);
            })
    }, [])

    return (
        <>
            <Head>
                <title>Publications :: Zernicka-Goetz Lab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout menuItems={menuItems} headerButton={filterOpen ? <ButtonIcon  type="close" callback={() => setFilterOpen(false)}/> : <ButtonIcon type="filter" callback={() => setFilterOpen(true)}/>}>
                <SearchFilterProvider>
                    <Filter open={filterOpen} setFilterOpen={setFilterOpen}/>
                    <Container>
                        <PublicationList pubs={pubs} />
                    </Container>
                </SearchFilterProvider>
            </Layout>
        </>
    )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}