import Head from 'next/head'
import styles from './home.module.scss';
import getMenu from '../utils/getMenu';

// COMPONENTS
import LloydRelaxation from '../components/LloydRelaxation/LloydRelaxation'
import Layout from '../components/Layout/Layout';

export default function Home({menuItems}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout menuItems={menuItems}>
        {/* <LloydRelaxation /> */}
      </Layout>

    </div>
  )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}