// STYLES
import styles from './home.module.scss';

// REACT
import {useState, useEffect} from 'react';

// NEXT JS
import Head from 'next/head'

// UTILITIES
import getMenu from '../utils/getMenu';
import getHome from '../utils/getHome';

// IMPORTED COMPONENTS
import LloydRelaxation from '../components/LloydRelaxation/LloydRelaxation'
import Layout from '../components/Layout/Layout';
import AlternatingContainer from '../components/AlternatingContainer/AlternatingContainer';
import HomeResearchContent from '../components/HomeResearchContent/HomeResearchContent';
import HomeCustomSection from '../components/HomeCustomSection/HomeCustomSection';
import HomeNewsSection from '../components/HomeNewsSection/HomeNewsSection';
import HomeBookSection from '../components/HomeBookSection/HomeBookSection';
import HomeMissionSection from '../components/HomeMissionSection/HomeMissionSection';
import HomePubsSection from '../components/HomePubsSection/HomePubsSection';

// HELPER COMPONENTS
const HomeContent = ({content, home}) => {
  return content.map( section => {
    if (section._type == "preBuilt") {
      if (section.type == "research") {
        return <HomeResearchContent text={section.researchText} images={section.researchImages} key={section._key}/>
      } else if (section.type == "news") {
        return <HomeNewsSection key={section._key} />
      } else if (section.type == "book") {
        return <HomeBookSection section={section} key={section._key} />
      } else if (section.type == "publications") {
        return <HomePubsSection image={section.image} key={section._key} />
      }
    } else {
      return <HomeCustomSection key={section._key} content={section}/>
    }
  })
}

export default function Home({menuItems}) {
  const [home, setHome] = useState(null);
  const [finishedScrolling, setFinishedScrolling] = useState(false);

  useEffect(() => {
    getHome()
      .then( res => {
        console.log(res)
        setHome(res);
      })
      .catch( err => {
        console.log(err);
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Zernicka-Goetz Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout menuItems={menuItems} finishedScrolling={finishedScrolling}>
        <LloydRelaxation setFinishedScrolling={setFinishedScrolling} finishedScrolling={finishedScrolling}/>
        { home && home.mission && <HomeMissionSection content={home.mission} />}
        <AlternatingContainer>
          {home && home.content && home.content.length > 0 ? <HomeContent home={home} content={home.content}/> : <></>}
        </AlternatingContainer>
      </Layout>

    </div>
  )
}

export async function getStaticProps({params}) {
  const menuItems = await getMenu();
  return {
    props: { menuItems }
  }
}